export const UPDATE_CALCULATION_AND_RESULT = 'UPDATE_CALCULATION_AND_RESULT';
export const CLEAR_ALL = 'CLEAR_ALL';
export const INPUT_VALUE = 'INPUT_VALUE';
export const INPUT_OPERATOR = 'INPUT_OPERATOR';
